### ISSUE TITLE
Add data files for Data Explorer Viz Module

### ISSUE THREAD

**Issue by cgettings** [nycehs/ehs-data-portal-frontend-temp#143]

**Comment by mmontesanonyc** [comment]
Thanks, Chris!
Great job getting this batch up.

I know we talked about some of this [here](https://github.com/nycehs/Portal-Prototype-Working-Files/issues/7), but I might need some documentation and reminding -

- Each indicator's filename corresponds to its `internal_id` in the database, which is called `IndicatorID` in `indicators.json`. 
- MeasureID - self explanatory
- MeasureName - this is essentially `IndicatorName` (from `indicators.json`) + `MeasurementType`
- MeasurementType - we'll use this for column headers, axis labels, etc.
- Geotype
- GeotypeID - Looks like a numeric code that corresponds to Geotype.
- GeoID - the geoID
- Time - the time period for the data
- Value - the data value
- Display value - the value that should be displayed. This is for instances where values are suppressed.
- CI: confidence interval (if present)
- Note: note associated with data point

Couple questions that I'll note in our requirements and display rules:
- What's the logic behind having GeotypeID in addition to Geotype?
- Display value - are there instances when we should show the value instead of the display value? Or are we always showing Display Value, but offering Value for download? 
- CI field - I looked at 1.json, which doesn't have CIs, but it does have the CI field in each node - because of this structure (being present but empty, instead of being absent), I assume that our CI logic would need to be `if CI field has contents` rather than `if CI field is present` to display CIs when necessary. Yes?

**Comment by cgettings** [comment]
1. I forgot to remove `GeotypeID`, which I was just using to sort the files. I'll update the exports.
2. Always showing display value, offering value (in place of, or in addition to)
3. Yes. I think it's probably better to have all the data files have the same structure, then test for contents. An empty CI adds `"CI":"",` to the JSON, which won't really make a difference in size. I think the logic could be "if any CI value string has length > 0".

**Comment by mmontesanonyc** [comment]
merged to [dev ](https://github.com/nycehs/ehs-data-portal-frontend-temp/pull/146)and [main](https://github.com/nycehs/ehs-data-portal-frontend-temp/pull/147)
